version: "3"

services:
  app:
    container_name: app
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    expose:
      - "3000"

  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
